before_install:
  - chmod +x mvnw
language: java
jdk:
  - oraclejdk8
services:
 - mysql
dist: trusty
sudo: required


script: mvn clean verify
after_success:
 - bash <(curl -s https://codecov.io/bash)
notifications:
email: false