before_install:
  - chmod +x mvnw
language: java
jdk:
  - oraclejdk8

sudo: requiredysql -u root -e "GRANT ALL ON Hackthon2.* TO 'Hackthon2'@'localhost';"

script: mvn clean verify
after_success:
 - bash <(curl -s https://codecov.io/bash)
notifications:
email: false